### ISSUE TITLE
Can't build claim tool - Do you guys want PRs?

### ISSUE THREAD

**Issue by marktellez** [BitcoinHEX/claim_tool#6]
✘ 21 problems (18 errors, 3 warnings)

I'll contribute a bit as a fan of the project (btchex) and of Richard's crazy wardrobe. :D

http://codementor.io/marktellez

**Comment by mesquka** [comment]
Claim tool is currently in limbo as some other stuff is restructured, PRs are welcome once we're on the road again though ;)
